version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bdms-mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "BDMS@20262802"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
